"""Render an Assessment as Markdown or self-contained HTML."""

from __future__ import annotations

import html

from azmigrate_check import __version__
from azmigrate_check.models import Assessment, Severity

_STATUS_LABEL = {"blocked": "Blocked", "review": "Needs review", "ready": "Ready"}


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _summary(a: Assessment) -> dict[str, int]:
    statuses = [a.server_status(s.name) for s in a.servers]
    return {
        "servers": len(a.servers),
        "ready": statuses.count("ready"),
        "review": statuses.count("review"),
        "blocked": statuses.count("blocked"),
        "blockers": a.count(Severity.BLOCKER),
        "warnings": a.count(Severity.WARNING),
        "info": a.count(Severity.INFO),
    }


def to_markdown(a: Assessment, title: str = "Azure Migration Readiness Report") -> str:
    s = _summary(a)
    lines = [
        f"# {title}",
        "",
        f"Assessment date: {a.as_of} · Generated by azmigrate-check {__version__}",
        "",
        "## Summary",
        "",
        "| Servers | Ready | Needs review | Blocked | Blockers | Warnings | Info |",
        "|---:|---:|---:|---:|---:|---:|---:|",
        f"| {s['servers']} | {s['ready']} | {s['review']} | {s['blocked']} "
        f"| {s['blockers']} | {s['warnings']} | {s['info']} |",
        "",
        "## Servers",
        "",
        "| Server | OS | vCPU | RAM (GB) | Status | Findings |",
        "|---|---|---:|---:|---|---:|",
    ]
    for srv in a.servers:
        os_text = _md_escape(f"{srv.os} {srv.os_version}".strip() or "-")
        lines.append(
            f"| {_md_escape(srv.name)} | {os_text} | {srv.cpu if srv.cpu is not None else '-'} "
            f"| {f'{srv.ram_gb:g}' if srv.ram_gb is not None else '-'} "
            f"| {_STATUS_LABEL[a.server_status(srv.name)]} | {len(a.findings_for(srv.name))} |"
        )
    lines += ["", "## Findings", ""]
    if not a.findings:
        lines.append("No findings. All servers passed the configured checks.")
    else:
        lines += [
            "| Severity | Rule | Server | Finding | Remediation |",
            "|---|---|---|---|---|",
        ]
        for f in a.findings:
            lines.append(
                f"| {f.severity.value.upper()} | {f.rule_id} | {_md_escape(f.server)} "
                f"| {_md_escape(f.message)} | {_md_escape(f.remediation)} |"
            )
    lines += [
        "",
        "> OS end-of-support dates come from a built-in catalog and may be overridden in "
        "config. Verify them against vendor lifecycle pages before making decisions.",
        "",
    ]
    return "\n".join(lines)


_CSS = """
:root{--bg:#fff;--fg:#1b1f24;--muted:#57606a;--line:#d0d7de;--card:#f6f8fa;
--blocker:#cf222e;--warning:#9a6700;--info:#0969da;--ready:#1a7f37}
@media (prefers-color-scheme:dark){:root{--bg:#0d1117;--fg:#e6edf3;--muted:#8d96a0;
--line:#30363d;--card:#161b22;--blocker:#ff7b72;--warning:#d29922;--info:#58a6ff;--ready:#3fb950}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);
font:15px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
main{max-width:1100px;margin:0 auto;padding:24px 16px}
h1{font-size:1.6rem;margin:0 0 4px}h2{font-size:1.2rem;margin:32px 0 12px}
.meta{color:var(--muted);margin:0}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;margin-top:20px}
.card{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:12px}
.card b{display:block;font-size:1.5rem}.card span{color:var(--muted);font-size:.85rem}
.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%}
th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{font-size:.8rem;text-transform:uppercase;letter-spacing:.03em;color:var(--muted)}
.num{text-align:right}.pill{display:inline-block;padding:1px 8px;border-radius:999px;
font-size:.8rem;font-weight:600;border:1px solid currentColor}
.blocker,.blocked{color:var(--blocker)}.warning,.review{color:var(--warning)}
.info{color:var(--info)}.ready{color:var(--ready)}
.note{color:var(--muted);font-size:.85rem;margin-top:24px}
"""


def to_html(a: Assessment, title: str = "Azure Migration Readiness Report") -> str:
    e = html.escape
    s = _summary(a)
    cards = [
        ("Servers", s["servers"], ""),
        ("Ready", s["ready"], "ready"),
        ("Needs review", s["review"], "review"),
        ("Blocked", s["blocked"], "blocked"),
        ("Blockers", s["blockers"], "blocker"),
        ("Warnings", s["warnings"], "warning"),
    ]
    card_html = "".join(
        f'<div class="card"><b class="{cls}">{val}</b><span>{e(label)}</span></div>'
        for label, val, cls in cards
    )
    server_rows = []
    for srv in a.servers:
        status = a.server_status(srv.name)
        server_rows.append(
            "<tr>"
            f"<td>{e(srv.name)}</td>"
            f"<td>{e(f'{srv.os} {srv.os_version}'.strip() or '-')}</td>"
            f'<td class="num">{srv.cpu if srv.cpu is not None else "-"}</td>'
            f'<td class="num">{f"{srv.ram_gb:g}" if srv.ram_gb is not None else "-"}</td>'
            f'<td><span class="pill {status}">{_STATUS_LABEL[status]}</span></td>'
            f'<td class="num">{len(a.findings_for(srv.name))}</td>'
            "</tr>"
        )
    if a.findings:
        finding_rows = "".join(
            "<tr>"
            f'<td><span class="pill {f.severity.value}">{f.severity.value.upper()}</span></td>'
            f"<td>{e(f.rule_id)}</td><td>{e(f.server)}</td>"
            f"<td>{e(f.message)}</td><td>{e(f.remediation)}</td>"
            "</tr>"
            for f in a.findings
        )
        findings_html = (
            '<div class="table-wrap"><table><thead><tr><th>Severity</th><th>Rule</th>'
            "<th>Server</th><th>Finding</th><th>Remediation</th></tr></thead>"
            f"<tbody>{finding_rows}</tbody></table></div>"
        )
    else:
        findings_html = "<p>No findings. All servers passed the configured checks.</p>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title>
<style>{_CSS}</style>
</head>
<body>
<main>
<h1>{e(title)}</h1>
<p class="meta">Assessment date: {e(a.as_of)} · Generated by azmigrate-check {e(__version__)}</p>
<div class="cards">{card_html}</div>
<h2>Servers</h2>
<div class="table-wrap"><table><thead><tr><th>Server</th><th>OS</th><th class="num">vCPU</th>
<th class="num">RAM (GB)</th><th>Status</th><th class="num">Findings</th></tr></thead>
<tbody>{"".join(server_rows)}</tbody></table></div>
<h2>Findings</h2>
{findings_html}
<p class="note">OS end-of-support dates come from a built-in catalog and may be overridden in
config. Verify them against vendor lifecycle pages before making decisions.</p>
</main>
</body>
</html>
"""
